package com.moraveco.challengeme.ui.register

val countries = listOf(
    "Czech Republic",
    "Slovakia",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Poland",
    "Austria",
    "Netherlands",
    "Belgium",
    "Switzerland",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Portugal",
    "Greece",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Croatia",
    "Serbia",
    "Slovenia",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Ireland",
    "United Kingdom",
    "Iceland",
    "Luxembourg",
    "Malta",
    "Cyprus"
)