package com.moraveco.challengeme.constants

class Constants {
    companion object{
        const val BASE_URL = "https://mymedevelopers.com/ChallangeMe/"
        const val LOGIN = "login2.php"
        const val BLOCK_USER = "blockUser.php"
        const val INSERT_USER = "insertUserData.php"
        const val REGISTER = "insertNewUser.php"
        const val ALL_USERS = "fetchAllUsers.php"
        const val USER_BY_ID = "getUserById.php"
        const val FOLLOW_USER = "insertFriend.php"
        const val FETCH_FOLLOW = "fetchFollowById.php"
        const val ACCEPT_FOLLOW = "acceptFriend.php"
        const val DELETE_FRIEND = "deleteFriend.php"
        const val DELETE_ACCOUNT = "deleteAccount.php"
        const val ALL_POSTS = "fetchAllPosts.php"
        const val PUBLIC_POSTS = "fetchPosts.php"
        const val FRIEND_POSTS = "fetchFriendPosts.php"
        const val POST_BY_ID = "fetchPostById.php"
        const val PROFILE_POSTS = "fetchMyPosts.php"
        const val FETCH_COMMENTS = "fetchComments.php"
        const val SEND_COMMENT = "sendComment.php"
        const val FETCH_LIKES = "fetchLikes.php"
        const val INSERT_LIKE = "insertLike.php"
        const val DELETE_LIKE = "deleteLike.php"
        const val FETCH_REQUESTS = "fetchFollowRequest.php"
        const val FETCH_FRIENDS = "fetchFriends.php"
        const val FETCH_NOTIFICATIONS = "fetchNotifications.php"
        const val UPDATE_POST = "editPost.php"
        const val DELETE_POST = "deletePost.php"
        const val UPDATE_PASS = "updatePassword.php"
        const val UPDATE_PROFILE = "updateProfile.php"
        const val SEND_PASS = "newPassword.php"
        const val SEND_NOTIFICATION = "sendnot.php"
        const val FETCH_TODAY_LEADERBOARD = "fetchLeaderboard.php"
        const val FETCH_GLOBAL_LEADERBOARD = "fetchGlobal.php"
        const val FETCH_FRIENDS_LEADERBOARD = "fetchFriendsLeaderBoard.php"
        const val FETCH_DAILY_CHALLENGE = "fetchDailyChallange.php"
        const val UPDATE_TOKEN = "uploadToken.php"
    }
}